logging:
  level:
    io.pivotal.demo.PolicyEnforceService: debug
     
spring:
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    admin: http://localhost:15673
    
  profiles:
    active: PolicyEnforcement   
    
plan:
  name: _plan
  allow-mirror-queues: false
  max-slaves: 1
  ha-sync-mode: manual  # manual or automatic (default)
  max-message-ttl: 60000
  queue-master-locator: min-masters  # min-masters, client-local(default), random
#  max-queue-length: 2000
#  max-queue-length-bytes: 7000
  