logging:
  level:
    io.pivotal.demo.PolicyEnforceService: debug
    
spring:
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    admin: http://localhost:15673
    
    
plan:
  name: _plan
  allow-mirror-queues: true
  max-slaves: 1
  maxMessageTTL: 60000
  max-queue-length: 2000
  max-queue-length-bytes: 7000
  